# Generated by Django 4.2.3 on 2023-07-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, default='Sold for cost', null=True),
        ),
    ]
