# Generated by Django 4.2.3 on 2023-07-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_prescriptionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='note',
            field=models.TextField(blank=True, default='Sold for cost', null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='note',
            field=models.TextField(blank=True, default='Sold for cost', null=True),
        ),
    ]
