# Generated by Django 4.2.3 on 2023-07-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_alter_prescription_note_alter_prescriptionitem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='customer_loan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
